// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "matrimonial/prisma/schema.prisma",
  migrations: {
    path: "matrimonial/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "postgresql://postgres.ycaeelqanntvzzcvqilu:Matrimonial_gagan@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres",
  },
});
