export const MOTHER_TONGUES = [
  "Hindi",
  "Bengali",
  "Punjabi",
  "Marathi",
  "Telugu",
  "Tamil",
  "Gujarati",
  "Urdu",
  "Kannada",
  "Odia",
  "Malayalam",
  "Assamese",
  "Maithili",
  "Marwari",
  "Bhojpuri",
  "Santali",
  "Kashmiri",
  "Nepali",
  "Konkani",
  "Sindhi",
  "Dogri",
  "English",
  "Other",
] as const;

export const EDUCATION_OPTIONS = [
  "B.Tech / B.E. / Engineering",
  "M.Tech / M.E. / MS",
  "BCA / MCA / Computer Science",
  "B.Sc / M.Sc / Science",
  "B.Com / M.Com / Commerce",
  "B.A / M.A / Arts / Humanities",
  "BBA / MBA / PGDM / Management",
  "MBBS / MD / MS / Medical",
  "BDS / MDS / Dental",
  "B.Pharm / M.Pharm / Pharmacy",
  "CA / CS / ICWA / Finance",
  "LLB / LLM / Law",
  "B.Arch / Architecture",
  "Ph.D / Doctorate",
  "Diploma / Polytechnic",
  "Higher Secondary / 12th Standard",
  "High School / 10th Standard",
  "Other",
] as const;

export const OCCUPATION_OPTIONS = [
  "Founder / Co-Founder / Entrepreneur",
  "Business Owner / Self-Employed",
  "Software Engineer / IT Professional",
  "Doctor / Healthcare Professional",
  "Chartered Accountant (CA) / CS / CFA",
  "Banker / Financial Analyst / Investment Banking",
  "Civil Services / IAS / IPS / IFS / Govt Officer",
  "Government / PSU Employee",
  "Management Consultant / Corporate Executive",
  "Marketing / Sales / PR Executive",
  "Lawyer / Legal Professional / Advocate",
  "Teacher / Professor / Academician",
  "Engineer (Mechanical / Civil / Electrical)",
  "Architect / Interior Designer",
  "HR / Operations / Admin",
  "Media / Journalist / Content Creator / Artist",
  "Aviation / Pilot / Cabin Crew",
  "Defense / Police / Armed Forces",
  "Scientist / Research Professional",
  "Merchant Navy / Maritime",
  "Real Estate / Builder / Developer",
  "Agriculture / Farming / Agro-Business",
  "Homemaker",
  "Not Employed / Looking for Job",
  "Other",
] as const;

export const FATHER_OCCUPATION_OPTIONS = [
  "Retired",
  "Govt Job / Government Employee",
  "Private Job / Private Sector",
  "Own Business / Self-Employed",
  "Civil Services / Defense / Police",
  "Doctor / Healthcare Professional",
  "Engineer / Technical Professional",
  "Teacher / Professor / Academician",
  "Banker / Financial Professional",
  "Lawyer / Legal Professional",
  "Farmer / Agriculture",
  "Passed Away",
  "Other",
] as const;

export const MOTHER_OCCUPATION_OPTIONS = [
  "HomeMaker",
  "Retired",
  "Govt Job / Government Employee",
  "Private Job / Private Sector",
  "Own Business / Self-Employed",
  "Teacher / Professor / Academician",
  "Doctor / Healthcare Professional",
  "Banker / Financial Professional",
  "Civil Services / Defense",
  "Lawyer / Legal Professional",
  "Passed Away",
  "Other",
] as const;

export type OccupationOption = (typeof OCCUPATION_OPTIONS)[number];
export type FatherOccupationOption = (typeof FATHER_OCCUPATION_OPTIONS)[number];
export type MotherOccupationOption = (typeof MOTHER_OCCUPATION_OPTIONS)[number];
