export const MOTHER_TONGUES = [
  "Hindi",
  "Bengali",
  "Punjabi",
  "Marathi",
  "Telugu",
  "Tamil",
  "Gujarati",
  "Urdu",
  "Kannada",
  "Odia",
  "Malayalam",
  "Assamese",
  "Maithili",
  "Marwari",
  "Bhojpuri",
  "Santali",
  "Kashmiri",
  "Nepali",
  "Konkani",
  "Sindhi",
  "Dogri",
  "Himachali",
  "Himachali (Kangri)",
  "Himachali (Mandeali)",
  "Pahari",
  "English",
  "Other",
] as const;

export const EDUCATION_OPTIONS = [
  "B.Tech / B.E. / Engineering",
  "M.Tech / M.E. / MS",
  "BCA / MCA / Computer Science",
  "B.Sc / M.Sc / Science",
  "B.Com / M.Com / Commerce",
  "B.A / M.A / Arts / Humanities",
  "BBA / MBA / PGDM / Management",
  "MBBS / MD / MS / Medical",
  "BDS / MDS / Dental",
  "B.Pharm / M.Pharm / Pharmacy",
  "CA / CS / ICWA / Finance",
  "LLB / LLM / Law",
  "B.Arch / Architecture",
  "Ph.D / Doctorate",
  "Diploma / Polytechnic",
  "Higher Secondary / 12th Standard",
  "High School / 10th Standard",
  "Other",
] as const;

export const OCCUPATION_OPTIONS = [
  "Software Engineer / IT Professional",
  "Doctor / Healthcare Professional",
  "Civil Services / IAS / IPS / IFS",
  "Government / PSU Employee",
  "Banker / Financial Analyst",
  "Chartered Accountant (CA)",
  "Business Owner / Entrepreneur",
  "Teacher / Professor / Academician",
  "Mechanical / Civil / Electrical Engineer",
  "Lawyer / Legal Professional",
  "Defense / Police / Armed Forces",
  "Architect / Interior Designer",
  "Marketing / Sales / PR Executive",
  "HR / Operations / Admin",
  "Media / Journalist / Content Creator",
  "Scientist / Research Professional",
  "Aviation / Pilot / Cabin Crew",
  "Merchant Navy / Maritime",
  "Consultant / Strategy Advisor",
  "Retail / Trading Business",
  "Manufacturing / Industrial Business",
  "Real Estate / Construction Business",
  "Hospitality / Hotel / Restaurant Business",
  "Finance / Investment Business",
  "IT / Startup / Tech Business",
  "Agriculture / Farming Business",
  "Self Employed",
  "Homemaker / Not Employed",
  "Other",
] as const;

export const FATHER_OCCUPATION_OPTIONS = [
  "Business / Entrepreneur",
  "Private Sector Service",
  "Government / PSU Employee",
  "Retired",
  "Civil Services / Defense / Police",
  "Doctor / Healthcare Professional",
  "Engineer / Technical Professional",
  "Teacher / Professor / Academician",
  "Banker / Financial Professional",
  "Lawyer / Legal Professional",
  "Farmer / Agriculture",
  "Self Employed",
  "Passed Away",
  "Other",
] as const;

export const MOTHER_OCCUPATION_OPTIONS = [
  "Homemaker",
  "Teacher / Professor / Academician",
  "Business / Entrepreneur",
  "Government / PSU Employee",
  "Private Sector Service",
  "Doctor / Healthcare Professional",
  "Banker / Financial Professional",
  "Civil Services / Defense",
  "Lawyer / Legal Professional",
  "Self Employed",
  "Passed Away",
  "Other",
] as const;
